from collections import defaultdict
import datetime
from email.policy import default
from platform import processor

from numpy import product
from mongoengine import *
from mongoengine import Document,  DateTimeField, StringField, FloatField, IntField, connect, BooleanField, ListField

connect("ecommerce")

class Category(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    item_category = StringField()
    segment = StringField()
    gpu_model = StringField()

class RawCategory(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    item_category = StringField()
    segment = StringField()

class Search(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    item_category = StringField()
    segment = StringField()
    
class SOV(Document):
    timestamp = DateTimeField()
    website = StringField()
    segment = StringField()
    total_count = IntField()
    brand = StringField()
    item_category = StringField()
    count = IntField()
    processor = StringField()
class SOS(Document):
    timestamp = DateTimeField()
    website = StringField()
    segment = StringField()
    total_count = IntField()
    brand = StringField()
    item_category = StringField()
    count = IntField()
    processor = StringField()
class WebsiteData(Document):
    timestamp = DateTimeField()
    all_count = IntField()
    non_ryzen_count = IntField()
    ryzen_count = IntField()
    website = StringField()
    amd_count = IntField()
    result_type = StringField()
    item_category = StringField()

class ReviewItems(Document):
    extract_date = DateTimeField(required=True)
    processor_type = StringField(required=True)
    processor_model = StringField(required=True)
    product_name = StringField(required=True)
    product_link = StringField(required=True)
    item_category = StringField(required=True)
    client = StringField(required=True)
    channel = StringField(required=True)
    review_count = IntField(required = True)
    brand_name = StringField(required=True)
    batch = StringField(required=True , default = 'A')
    last_updated =  DateTimeField()

class ReviewDocuments(Document):
    person_name = StringField(required = False, default = '')
    person_comment = StringField(required = False)
    person_comment_raw = StringField(required = False)
    review_date = DateTimeField(default = datetime.datetime.now)
    review_rating = FloatField(required = False)
    is_verfied_product = BooleanField(required = False)
    found_helpful = IntField(required = False)
    review_link = StringField(required = True)
    product_link = StringField(required = True)
    review_id = StringField(required = False)
    processor_type = StringField(required = True)
    processor_model = StringField(required = True)
    item_category = StringField(required = True )
    person_account_details = StringField(default='')  
    brand_name = StringField(required = True  )
    channel =  StringField(required = True)
    product_heading = StringField(required = True)
    product_name = StringField(required = True)
    product_id = StringField(required = True)
    extract_date = StringField(required=True)
    sponsored = BooleanField (required=True, default = False)
    client = StringField(required=True, default = 'amd')
    is_new =  BooleanField(required=True)
    product_rating = FloatField(required = False)

   
class ProductReviews(Document):
    person_name = StringField(required = False, default = '')
    person_comment = StringField(required = False)
    person_comment_raw = StringField(required = False)
    review_date = DateTimeField(default = datetime.datetime.now)
    review_rating = FloatField(required = False)
    product_rating = FloatField(required = False)
    is_verfied_product = BooleanField(required = False)
    found_helpful = IntField(required = False)
    review_link = StringField(required = True)
    product_link = StringField(required = True)
    review_id = StringField(required = False)
    processor_type = StringField(required = True)
    processor_model = StringField(required = True)
    item_category = StringField(required = True )
    person_account_details = StringField(default='')  
    brand_name = StringField(required = True  )
    channel =  StringField(required = True)
    product_heading = StringField(required = True)
    product_name = StringField(required = True)
    product_id = StringField(required = True)
    extract_date = StringField(required=True)
    sponsored = BooleanField (required=True, default = False)
    client = StringField(required=True, default = 'amd')
    new_review =  BooleanField(required=True)
    batch =  StringField(default='A')

class TranslateMap(Document):
    original = StringField()
    translated = StringField()
    source_language = StringField()


class AmazonCategoryIndia(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    brand = StringField()
    item_category = StringField()
    product_type = StringField()
    is_sponsor = StringField()
    is_premium = StringField()


class AmazonSearchIndia(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    brand = StringField()
    item_category = StringField()
    product_type = StringField()
    is_sponsor = StringField()
    is_premium = StringField()

class SOVDetails(Document):
    timestamp = DateTimeField()
    website = StringField()
    item_category = StringField()
    location = StringField()
    processor_model = StringField()
    processor_type = StringField()
    item_id = StringField()
    link = StringField()
    product_name = StringField()
    segment = StringField()


class RawSOVDetails(Document):
    timestamp = DateTimeField()
    website = StringField()
    item_category = StringField()
    location = StringField()
    processor_model = StringField()
    processor_type = StringField()
    item_id = StringField()
    link = StringField()
    product_name = StringField()
    segment = StringField()


class CategoryMediator(Document):
    timestamp = DateTimeField()
    website = StringField()
    ratings = FloatField()
    processor_type = StringField()
    offer = StringField()
    processor_model = StringField()
    price = StringField()
    page_count = IntField()
    processor_name = StringField()
    product_name = StringField()
    reviews = IntField()
    gpu_type = StringField()
    link = StringField()
    item_id = StringField()
    gpu = StringField()
    order = IntField()
    image_count = IntField()
    processor = StringField()
    page = IntField()
    brand_name = StringField()
    item_category = StringField()
    segment = StringField()
    completion = BooleanField(required = False, default = False)
    attempt_no = StringField()

status_codes = ("succeded","failed","running","unscheduled","scheduled","warning")
class StatusReporting(Document):
    
    timestamp = DateTimeField(default=datetime.datetime.now)
    spider_name = StringField()
    status = StringField(default="unscheduled",choices = status_codes)
    message = StringField(default = None)
    info = StringField(default = None)
    job_id = StringField(default=None)

class AllSpiders(Document):
    website = StringField()
    spider_name = StringField()


class ConsumerCompliance(Document):
    link = StringField()
    product_name = StringField()
    item_category = StringField()
    brand_name = StringField()
    processor_type = StringField()
    processor_model = StringField()
    ratings = FloatField()
    item_id = StringField()
    product_text = StringField()
    hero_text = StringField()
    other_text = StringField()
    product_diff = StringField()
    hero_diff = StringField()
    other_diff = StringField()
    product_text_match = StringField()
    hero_text_match = StringField()
    other_text_match = StringField()
    product_text_comment = StringField()
    hero_text_comment = StringField()
    other_text_comment = StringField()
    messaging_match = StringField()
    cpu_logo = StringField()
    gpu_logo = StringField()
    segment1 = StringField()
    segment2 = StringField()
    website = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    new_item = BooleanField(default = True)
    complete = BooleanField(default = False)
    logo_matched = BooleanField(default = False)
    review_scraped = BooleanField(default = False)

class ConsumerMessaging(Document):
    website = StringField()
    index = IntField()
    score = IntField()
    item_category = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    item_id = StringField()
    message = StringField()
    heading = StringField()
    comment = StringField()
    new_item = BooleanField(default = True)
    
class AllPrice(Document):
    website = StringField()
    item_category = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    processor = StringField()
    price = StringField()

class AmazonProductAnalyzer(Document):
    product_url = StringField()
    product_name = StringField()
    product_asin = StringField()
    job_id = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    symbols_and_emojis_not_in_title = BooleanField()
    title_length = IntField()
    bullet_count = IntField()
    bullet_points_length = ListField()
    bullet_first_letter_capital = BooleanField()
    bullet_not_all_caps = BooleanField()
    description_length = IntField()
    main_image_url = StringField()
    main_image_size = ListField()
    main_image_background_white = BooleanField()
    image_count = IntField()
    includes_video = BooleanField()
    reviews = IntField()
    ratings = FloatField()
    request_id = StringField(default=None)
    email = StringField(default=None)

class PincodeAvailabilityTracker(Document):
    website = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    item_id = StringField()
    product_name = StringField()
    product_url = StringField()
    brand_name = StringField()
    client = StringField()
    item_category = StringField()
    segment = StringField()
    location = StringField()
    pincode = StringField()
    availability = BooleanField()
    original_price = StringField()
    discounted_price = StringField()

class PincodePriceTracker(Document):
    platform = StringField()
    website = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    item_id = StringField()
    product_name = StringField()
    product_url = StringField()
    brand_name = StringField()
    client = StringField()
    segment = StringField()
    item_category = StringField()
    location = StringField()
    pincode = StringField()
    availability = BooleanField()
    out_of_stocks = BooleanField()
    original_price = StringField()
    discounted_price = StringField()
    
class RequestInfo(Document):
    job_id = StringField()
    spider_name = StringField()
    status = StringField()
    asin_count = IntField()
    eta = StringField()
    timestamp = DateTimeField(default = datetime.datetime.now)
    message = StringField(default=None)

class JDLinksForReviews(Document):
    product_url = StringField()
    item_category = StringField()
    # batch = StringField(max_length=2)
    status = BooleanField(default=False)
    timestamp = DateTimeField(default = datetime.datetime.today)